### ISSUE TITLE
Develop Frontend

### ISSUE THREAD

**Issue by Monish2218** [Monish2218/vidoo#1]
# Overview
We already have a partially developed frontend, now we have to enhance it by completing the following tasks.

# Intended Outcome
Develop a fully functional frontend.

# Tasks
- [x] Add a Home Page
- [x] Fix Navigation across the application
- [x] Connect Frontend to Backend
- [x] Add User Context
- [x] Make application responsive
