### ISSUE TITLE
Future Improvements

### ISSUE THREAD

**Issue by Monish2218** [Monish2218/vidoo#3]
# Overview

Below are some of the improvements that can be (or need to be) done After building a working solution:

# Tasks

- [ ] Improve the auth strategy
- [ ] Improve UI / UX
- [ ] Migrate Backend to TypeScript
- [ ] Perform required Validations at each step
- [ ] Add Tests
- [ ]
